/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BGGUI;

import BGBLL.BGUsername;

import BGDAL.BGUsernameDAL;
import java.awt.Desktop;
import java.net.URI;

import javax.swing.JOptionPane;

/**
 *
 * @author Bastian
 */
public class BGLoginGui extends javax.swing.JFrame {

    /**
     * Creates new form BGLoginGui
     */
    public BGLoginGui() {
        initComponents();
    }
public static int id = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        iconojava = new javax.swing.JLabel();
        iconoMYSQL = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnIngresar = new javax.swing.JButton();
        txtError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BGImagenes/icons8_Dropbox_64.png"))); // NOI18N
        jLabel1.setText("Dropbox");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 140, -1));

        iconojava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BGImagenes/icons8_Java_64.png"))); // NOI18N
        getContentPane().add(iconojava, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 50));

        iconoMYSQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BGImagenes/icons8_MySQL_64.png"))); // NOI18N
        getContentPane().add(iconoMYSQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, 60));

        btnSalir.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 0, 0));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BGImagenes/cerrar_32.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 30, 30));

        jLabel9.setBackground(new java.awt.Color(234, 169, 45));
        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(250, 194, 47));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("IPCHILENO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 160, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BGImagenes/Bank-icon.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 270));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BGImagenes/iconouser_32.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 30, 30));

        txtUsuario.setBackground(new java.awt.Color(33, 67, 115));
        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setText("Usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 130, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 180, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BGImagenes/fondoLogin.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 440));

        jPanel1.setBackground(new java.awt.Color(33, 67, 115));
        jPanel1.setForeground(new java.awt.Color(33, 67, 115));
        jPanel1.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BGImagenes/iconoLogin.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-3, 5, 256, 256);

        txtContraseña.setBackground(new java.awt.Color(33, 67, 115));
        txtContraseña.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraseña.setText("Contraseña");
        txtContraseña.setToolTipText("");
        txtContraseña.setBorder(null);
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseClicked(evt);
            }
        });
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(txtContraseña);
        txtContraseña.setBounds(70, 349, 130, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BGImagenes/iconocontrasena_32.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 332, 30, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(40, 370, 180, 10);

        btnIngresar.setBackground(new java.awt.Color(0, 0, 51));
        btnIngresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Iniciar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar);
        btnIngresar.setBounds(90, 380, 80, 31);

        txtError.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(txtError);
        txtError.setBounds(50, 320, 190, 20);

        jLabel7.setText("Desarrollador : Bastian Gonzalez");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 420, 235, 15);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 250, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       BGUsername us = new BGUsername();
        BGUsernameDAL user = new BGUsernameDAL();
    //    BGUsuario usnuevo = new BGUsuario();
        
    //  int res = -1;
        
        try
        {
            if(txtUsuario.getText().isEmpty() && txtContraseña.getText().isEmpty()){
                txtError.setText("Campos Vacios");
            }
            else if(txtUsuario.getText().isEmpty()){
                txtError.setText("Campo Usuario Vacio");
            }
            else if(txtContraseña.getText().isEmpty()){
                txtError.setText("Campo Contraseña Vacio");
              }
            else{
                txtError.setText(null);
            }
             String username = this.txtUsuario.getText();
             String pass =this.txtContraseña.getText();
            // us.setPass(this.txtContraseña.getText());
             us = user.Conectar(username,pass);
             if (us.getUsername()==null) {
                us.setEstado(-1);
            }
            switch(us.getEstado())
            {
                case 0:
                   
                  
                   JOptionPane.showMessageDialog(null, "Username : "+us.getUsername()+" Inactivo");
                     break;
                case 1:
                    id = us.getId_usuario();
                   BGMenuGUI menu = new BGMenuGUI();
                    menu.setLocationRelativeTo(null);
                    menu.setVisible(true);
                     dispose();
                    break;
                default :
                    JOptionPane.showMessageDialog(null, "Usuario Contraseña Incorrectos");
                    break;
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Problemas Login");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        // TODO add your handling code here:
        if(txtUsuario.getText().length() > 10){
            getToolkit().beep();
            evt.consume();
         txtError.setText("Ingrese Solo 9 Digitos");
            }
      else
        {
            txtError.setText(null);
      }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        // TODO add your handling code here:
        this.txtUsuario.setText(null);
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void txtContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseClicked
        // TODO add your handling code here:
        this.txtContraseña.setText(null);
    }//GEN-LAST:event_txtContraseñaMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       if(java.awt.Desktop.isDesktopSupported()){
 try{
      Desktop dk = Desktop.getDesktop();
      dk.browse(new URI("https://www.dropbox.com/sh/kxhoetgwba0x1ck/AAAdKDt8bdz5eYlLVDHFDyUba?dl=0"));
 }catch(Exception e){
     System.out.println("Error al abrir URL: "+e.getMessage());  
     }
}
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BGLoginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BGLoginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BGLoginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BGLoginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BGLoginGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel iconoMYSQL;
    private javax.swing.JLabel iconojava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JLabel txtError;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
